-- 单品SKU成本表
CREATE TABLE IF NOT EXISTS eb_sku_costs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(100) NOT NULL COMMENT '商品SKU',
  name VARCHAR(255) DEFAULT '' COMMENT '中文名称',
  purchase_price DECIMAL(10,4) DEFAULT 0 COMMENT '采购单价(CNY)',
  packaging_cost DECIMAL(10,4) DEFAULT 3.2 COMMENT '包材费(CNY)',
  warehouse_fee DECIMAL(10,4) DEFAULT 0 COMMENT '仓储费(CNY)',
  status TINYINT DEFAULT 1 COMMENT '1启用 0停用',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sku (sku),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单品SKU成本表';

-- 组合SKU关系表
CREATE TABLE IF NOT EXISTS eb_sku_combos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  combo_sku VARCHAR(200) NOT NULL COMMENT '组合SKU',
  combo_name VARCHAR(255) DEFAULT '' COMMENT '组合名称',
  item_sku VARCHAR(100) NOT NULL COMMENT '子单品SKU',
  quantity INT DEFAULT 1 COMMENT '数量',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_combo_sku (combo_sku),
  INDEX idx_item_sku (item_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组合SKU关系表';
